apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbsrn-api
  namespace: mbsrn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mbsrn-api
  template:
    metadata:
      labels:
        app: mbsrn-api
    spec:
      containers:
        - name: mbsrn-api
          image: __API_IMAGE__
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
