apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - api-deployment.yaml
  - api-seo-competitor-profile-retention-cronjob.yaml
  - api-service.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - frontend-config.yaml
  - managed-certificate.yaml
  - ingress.yaml
