apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: work-boots-dev
resources:
  - namespace.yaml
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: work-boots-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: development
      - op: replace
        path: /data/NEXT_PUBLIC_API_BASE_URL
        value: https://dev.workboots.example.com
      - op: replace
        path: /data/GOOGLE_BUSINESS_PROFILE_REDIRECT_URI
        value: https://dev.workboots.example.com/api/integrations/google/business-profile/connect/callback
  - target:
      kind: Ingress
      name: work-boots-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.workboots.example.com
  - target:
      kind: Deployment
      name: work-boots-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: work-boots-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
